// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: application.sql

package db

import (
	"context"
	"strings"
	"time"

	"github.com/samber/mo"
	"watools/pkg/models"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO application (id, name, description, category, path, icon_path, dir_updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, name, description, category, path, icon_path, updated_at, dir_updated_at, last_used_at, used_count
`

type CreateApplicationParams struct {
	ID           string
	Name         string
	Description  mo.Option[string]
	Category     string
	Path         string
	IconPath     mo.Option[string]
	DirUpdatedAt time.Time
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplication,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Path,
		arg.IconPath,
		arg.DirUpdatedAt,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Path,
		&i.IconPath,
		&i.UpdatedAt,
		&i.DirUpdatedAt,
		&i.LastUsedAt,
		&i.UsedCount,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE
FROM application
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) DeleteApplication(ctx context.Context, ids []string) error {
	query := deleteApplication
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getApplicationIsUpdatedDir = `-- name: GetApplicationIsUpdatedDir :one
SELECT id, name, description, category, path, icon_path, updated_at, dir_updated_at, last_used_at, used_count
FROM application
WHERE dir_updated_at != ?1
  AND path = ?2
LIMIT 1
`

type GetApplicationIsUpdatedDirParams struct {
	DirUpdatedAt time.Time
	Path         string
}

func (q *Queries) GetApplicationIsUpdatedDir(ctx context.Context, arg GetApplicationIsUpdatedDirParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplicationIsUpdatedDir, arg.DirUpdatedAt, arg.Path)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Path,
		&i.IconPath,
		&i.UpdatedAt,
		&i.DirUpdatedAt,
		&i.LastUsedAt,
		&i.UsedCount,
	)
	return i, err
}

const getApplications = `-- name: GetApplications :many
SELECT id, name, description, category, path, icon_path, updated_at, dir_updated_at, last_used_at, used_count
FROM application
`

func (q *Queries) GetApplications(ctx context.Context) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, getApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Path,
			&i.IconPath,
			&i.UpdatedAt,
			&i.DirUpdatedAt,
			&i.LastUsedAt,
			&i.UsedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredApplications = `-- name: GetExpiredApplications :many
SELECT id, name, description, category, path, icon_path, updated_at, dir_updated_at, last_used_at, used_count
FROM application
WHERE updated_at < ?1
`

func (q *Queries) GetExpiredApplications(ctx context.Context, updatedAt time.Time) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredApplications, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Path,
			&i.IconPath,
			&i.UpdatedAt,
			&i.DirUpdatedAt,
			&i.LastUsedAt,
			&i.UsedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationPartial = `-- name: UpdateApplicationPartial :exec
UPDATE application
SET name           = COALESCE(?1, name),
    description    = COALESCE(?2, description),
    category       = COALESCE(?3, category),
    path           = COALESCE(?4, path),
    icon_path      = COALESCE(?5, icon_path),
    dir_updated_at = COALESCE(?6, dir_updated_at),
    updated_at     = datetime('now', 'localtime')
WHERE id = ?7
`

type UpdateApplicationPartialParams struct {
	Name         mo.Option[string]
	Description  mo.Option[string]
	Category     mo.Option[string]
	Path         mo.Option[string]
	IconPath     mo.Option[string]
	DirUpdatedAt time.Time
	ID           string
}

func (q *Queries) UpdateApplicationPartial(ctx context.Context, arg UpdateApplicationPartialParams) error {
	_, err := q.db.ExecContext(ctx, updateApplicationPartial,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Path,
		arg.IconPath,
		arg.DirUpdatedAt,
		arg.ID,
	)
	return err
}

const updateApplicationUsage = `-- name: UpdateApplicationUsage :exec
UPDATE application
SET last_used_at = ?1,
    used_count   = ?2,
    updated_at   = datetime('now', 'localtime')
WHERE id = ?3
`

type UpdateApplicationUsageParams struct {
	LastUsedAt models.OptionTime
	UsedCount  int64
	ID         string
}

func (q *Queries) UpdateApplicationUsage(ctx context.Context, arg UpdateApplicationUsageParams) error {
	_, err := q.db.ExecContext(ctx, updateApplicationUsage, arg.LastUsedAt, arg.UsedCount, arg.ID)
	return err
}
