// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/samber/mo"
	"watools/pkg/models"
)

type Application struct {
	ID           string
	Name         string
	Description  mo.Option[string]
	Category     string
	Path         string
	IconPath     mo.Option[string]
	UpdatedAt    time.Time
	DirUpdatedAt time.Time
	LastUsedAt   models.OptionTime
	UsedCount    int64
}

type Metadata struct {
	Key   string
	Value mo.Option[string]
}

type PluginState struct {
	PackageID  string
	Enabled    bool
	Storage    string
	LastUsedAt models.OptionTime
	UsedCount  int64
}
