// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Command struct {
	ID          int64
	Name        string
	Description string
	Category    string
	Path        string
	IconPath    string
	CreatedAt   string
	UpdatedAt   string
	IsDeleted   bool
}

type Metadata struct {
	Key   string
	Value sql.NullString
}
