// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Application struct {
	ID           string
	Name         string
	Description  string
	Category     string
	Path         string
	IconPath     string
	UpdatedAt    string
	DirUpdatedAt string
}

type Metadata struct {
	Key   string
	Value sql.NullString
}

type PluginState struct {
	PackageID    string
	Enabled      bool
	Storage      string
	LastUsedTime string
	UsedCount    int64
}
