// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetApplicationCommandsApi():Promise<Array<any>>;

export function GetOperatorCommandsApi():Promise<Array<any>>;

export function GetPluginsApi():Promise<Array<Record<string, any>>>;

export function HideAppApi():Promise<void>;

export function HideOrShowAppApi():Promise<void>;

export function TriggerCommandApi(arg1:string,arg2:string):Promise<void>;
