// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetApplicationCommandsApi() {
  return window['go']['coordinator']['WaAppCoordinator']['GetApplicationCommandsApi']();
}

export function GetClipboardContentApi() {
  return window['go']['coordinator']['WaAppCoordinator']['GetClipboardContentApi']();
}

export function GetOperatorCommandsApi() {
  return window['go']['coordinator']['WaAppCoordinator']['GetOperatorCommandsApi']();
}

export function GetPluginJsEntryUrlApi(arg1) {
  return window['go']['coordinator']['WaAppCoordinator']['GetPluginJsEntryUrlApi'](arg1);
}

export function GetPluginsApi() {
  return window['go']['coordinator']['WaAppCoordinator']['GetPluginsApi']();
}

export function HideAppApi() {
  return window['go']['coordinator']['WaAppCoordinator']['HideAppApi']();
}

export function HideOrShowAppApi() {
  return window['go']['coordinator']['WaAppCoordinator']['HideOrShowAppApi']();
}

export function HttpProxyApi(arg1) {
  return window['go']['coordinator']['WaAppCoordinator']['HttpProxyApi'](arg1);
}

export function InstallPluginApi(arg1) {
  return window['go']['coordinator']['WaAppCoordinator']['InstallPluginApi'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['coordinator']['WaAppCoordinator']['OpenFolder'](arg1);
}

export function SaveBase64Image(arg1) {
  return window['go']['coordinator']['WaAppCoordinator']['SaveBase64Image'](arg1);
}

export function TogglePluginApi(arg1, arg2) {
  return window['go']['coordinator']['WaAppCoordinator']['TogglePluginApi'](arg1, arg2);
}

export function TriggerCommandApi(arg1, arg2) {
  return window['go']['coordinator']['WaAppCoordinator']['TriggerCommandApi'](arg1, arg2);
}

export function UninstallPluginApi(arg1) {
  return window['go']['coordinator']['WaAppCoordinator']['UninstallPluginApi'](arg1);
}

export function UpdateApplicationUsageApi(arg1) {
  return window['go']['coordinator']['WaAppCoordinator']['UpdateApplicationUsageApi'](arg1);
}

export function UpdatePluginUsageApi(arg1) {
  return window['go']['coordinator']['WaAppCoordinator']['UpdatePluginUsageApi'](arg1);
}
