// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetApplicationCommandsApi():Promise<Array<any>>;

export function GetOperatorCommandsApi():Promise<Array<any>>;

export function GetPluginExecEntryApi(arg1:string):Promise<string>;

export function GetPluginsApi():Promise<Array<models.Plugin>>;

export function HideAppApi():Promise<void>;

export function HideOrShowAppApi():Promise<void>;

export function ReloadApi():Promise<void>;

export function ReloadAppApi():Promise<void>;

export function TriggerCommandApi(arg1:string,arg2:string):Promise<void>;
