// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetApplicationCommandsApi() {
  return window['go']['coordinator']['WaAppCoordinator']['GetApplicationCommandsApi']();
}

export function GetOperatorCommandsApi() {
  return window['go']['coordinator']['WaAppCoordinator']['GetOperatorCommandsApi']();
}

export function HideAppApi() {
  return window['go']['coordinator']['WaAppCoordinator']['HideAppApi']();
}

export function HideOrShowAppApi() {
  return window['go']['coordinator']['WaAppCoordinator']['HideOrShowAppApi']();
}

export function ReloadApi() {
  return window['go']['coordinator']['WaAppCoordinator']['ReloadApi']();
}

export function ReloadAppApi() {
  return window['go']['coordinator']['WaAppCoordinator']['ReloadAppApi']();
}

export function TriggerCommandApi(arg1, arg2) {
  return window['go']['coordinator']['WaAppCoordinator']['TriggerCommandApi'](arg1, arg2);
}
