// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function GetApplication():Promise<Array<models.Command>>;

export function GetIconBase64(arg1:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
