// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetApplications() {
  return window['go']['launch']['WaLaunchApp']['GetApplications']();
}

export function RunApplication(arg1) {
  return window['go']['launch']['WaLaunchApp']['RunApplication'](arg1);
}

export function Startup(arg1) {
  return window['go']['launch']['WaLaunchApp']['Startup'](arg1);
}
