// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetApplication() {
  return window['go']['launch']['WaLaunchApp']['GetApplication']();
}

export function Startup(arg1) {
  return window['go']['launch']['WaLaunchApp']['Startup'](arg1);
}
