// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIconBase64(arg1) {
  return window['go']['apps']['WaApp']['GetIconBase64'](arg1);
}

export function GetSystemApplication() {
  return window['go']['apps']['WaApp']['GetSystemApplication']();
}

export function InitWindowSize(arg1) {
  return window['go']['apps']['WaApp']['InitWindowSize'](arg1);
}
