// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnablePanelBehavior() {
  return window['go']['app']['WaApp']['EnablePanelBehavior']();
}

export function GetHotkeys() {
  return window['go']['app']['WaApp']['GetHotkeys']();
}

export function HideApp() {
  return window['go']['app']['WaApp']['HideApp']();
}

export function HideAppWithFocusReturn() {
  return window['go']['app']['WaApp']['HideAppWithFocusReturn']();
}

export function HideOrShowApp() {
  return window['go']['app']['WaApp']['HideOrShowApp']();
}

export function Reload() {
  return window['go']['app']['WaApp']['Reload']();
}

export function ReloadAPP() {
  return window['go']['app']['WaApp']['ReloadAPP']();
}

export function ShowApp() {
  return window['go']['app']['WaApp']['ShowApp']();
}

export function ShowAppAsPanel() {
  return window['go']['app']['WaApp']['ShowAppAsPanel']();
}

export function Shutdown(arg1) {
  return window['go']['app']['WaApp']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['WaApp']['Startup'](arg1);
}

export function UpdateHotkey(arg1) {
  return window['go']['app']['WaApp']['UpdateHotkey'](arg1);
}
