// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function GetHotkeys():Promise<Array<app.HotkeyConfigAPI>>;

export function HideApp():Promise<void>;

export function HideOrShowApp():Promise<void>;

export function Reload():Promise<void>;

export function ReloadAPP():Promise<void>;

export function ShowApp():Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateHotkey(arg1:app.HotkeyConfigAPI):Promise<void>;
