// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitWindowSize(arg1) {
  return window['go']['app']['WaApp']['InitWindowSize'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['WaApp']['Startup'](arg1);
}
