// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HideApp() {
  return window['go']['app']['WaApp']['HideApp']();
}

export function HideOrShowApp() {
  return window['go']['app']['WaApp']['HideOrShowApp']();
}

export function RegisterHotkeys() {
  return window['go']['app']['WaApp']['RegisterHotkeys']();
}

export function ShowApp() {
  return window['go']['app']['WaApp']['ShowApp']();
}

export function Startup(arg1) {
  return window['go']['app']['WaApp']['Startup'](arg1);
}
