// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function HideOrShow():Promise<void>;

export function InitWindowSize():Promise<void>;

export function ListenHotkeys():Promise<void>;

export function RegisterHotkeys():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
