// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {watcher} from '../models';
import {context} from '../models';

export function GetApplicationCommands():Promise<Array<any>>;

export function GetOperationCommands():Promise<Array<any>>;

export function GetWatchMetrics():Promise<watcher.WatcherMetrics>;

export function GetWatchStatus():Promise<Record<string, any>>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function TriggerCommand(arg1:string):Promise<void>;
