// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllCommands() {
  return window['go']['command']['WaLaunchApp']['GetAllCommands']();
}

export function GetWatchMetrics() {
  return window['go']['command']['WaLaunchApp']['GetWatchMetrics']();
}

export function GetWatchStatus() {
  return window['go']['command']['WaLaunchApp']['GetWatchStatus']();
}

export function Shutdown(arg1) {
  return window['go']['command']['WaLaunchApp']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['command']['WaLaunchApp']['Startup'](arg1);
}

export function TriggerCommand(arg1) {
  return window['go']['command']['WaLaunchApp']['TriggerCommand'](arg1);
}
